POLLING_INTERVAL = 1  # seconds

# Test Creation Defaults
DEFAULT_MAX_WAIT_TIME: int = 120
DEFAULT_NUM_QUESTIONS: int = 20
DEFAULT_TEST_LANGUAGE: str = "en"

# Input Limit Defaults
DEFAULT_TEST_NAME_LEN_MIN: int = 1
DEFAULT_TEST_NAME_LEN_MAX: int = 100
DEFAULT_NUM_QUESTIONS_MIN: int = 1
DEFAULT_NUM_QUESTIONS_MAX: int = 150
DEFAULT_CHAR_TO_TOKEN_MULTIPLIER: float = 0.15
DEFAULT_MAX_TOKENS: int = 100000
